### ISSUE TITLE
VerifyPassword should use an escaping closure

### ISSUE THREAD

**Issue by magnusahlberg** [IBM-Swift/Kitura-CredentialsHTTP#37]
# Issue descriptioon

VerifyPassword is currently defined as follows (with a nonescaping closure for UserProfile):
`public typealias VerifyPassword = (String, String, (UserProfile?)->Void) -> Void`

However, when using e.g. Kuery for doing DB lookups to verify passwords from a database, DB query functions are escaping. This results in code like the following example:

```
let basicCredentials = CredentialsHTTPBasic( verifyPassword: { userID, password, callback in
    let query = Select(users.email, users.password, from: users)
        .where(users.email == userID)

    connection.execute(query: query) { result in
        if let rows = result.asRows {
            if let truePassword = rows[0]["password"] as? String {
                if truePassword == password {
                    callback(UserProfile(id: userID, displayName: userID, provider: "HTTPBasic-Kitura"))
                    return
                }
            }
        callback(nil)
    }
})
```

In this case the Swift Complier will generate an error:

> Closure use of non-escaping parameter 'callback' may allow it to escape

# Suggested fix

Change VerifyPassword typealias to use an explicitly escaping closure:

`public typealias VerifyPassword = (String, String, @escaping(UserProfile?)->Void) -> Void`

**Comment by irar2** [comment]
Fixed.
