### ISSUE TITLE
issue: The manifest file at https://github.com/IBM-Swift/CommonCrypto.git (0.1.3) is empty

### ISSUE THREAD

**Issue by ghost** [IBM-Swift/Kitura-CredentialsHTTP#46]
How do i resolve this issue?
thanks

**Comment by rchatham** [comment]
This is also the same as https://github.com/IBM-Swift/Kitura-CredentialsHTTP/issues/45

**Comment by rchatham** [comment]
Having the same issue

**Comment by Andrew-Lees11** [comment]
@diuming Hello.
This issue is caused when there is a conflict in your package.swift file. see issue #45 for a similar problem. We are tagging a fix now which should solve this in most cases.

**Comment by ghost** [comment]
@Andrew-Lees11 Hi,
the problem has been solved.
Thanks!
