### ISSUE TITLE
Authenticating specific resources?

### ISSUE THREAD

**Issue by collinhundley** [IBM-Swift/Kitura-CredentialsHTTP#8]
What's the recommended way to authenticate for specific resources using HTTP Basic Auth?

For example, suppose I have an endpoint to POST a message for a certain conversation:

``` swift
router.post("/messages") { (request, response, next) in
    // Extract conversation UUID from request body...
    let uuid = UUID_FROM_BODY
    // Post the message for this conversation, etc...
    // Respond to client
    response.status(.accepted) 
}
```

But only certain users are authorized to POST for certain conversations. A `UserProfileLoader` allows me to check for the _existence_ of a user and confirm their password, but how can I confirm that they have access to a specific resource? E.g. in the example above, I would need to pass the conversation UUID to a `UserProfileLoader` function in addition to the `userId`.

**Comment by irar2** [comment]
We only support authentication (and not authorization) at the moment, so you can't  check if a user is authorized to perform specific action.
